linters:
  disable-all: true
  enable:
    - bodyclose
    # - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    # - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    # - gomnd
    - goprintffuncname
    # - gosec
    - gosimple
    - govet
    # ??????
    # - ineffassign
    - revive
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    # - unused
    # - varcheck #unused var check
    - whitespace
    - revive
